apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-core
  namespace: monitoring
  labels:
    app: grafana
    component: core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
        component: core
    spec:
      containers:
      - env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-username
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-password
        name: grafana-graph
        image: gcr.io/lv-401-devops/img_grafana:latest
        ports: 
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
           #initialDelaySeconds: 30
           #timeoutSeconds: 1
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-db-storage
      volumes:
      - name: grafana-db-storage
        persistentVolumeClaim:
          claimName: grafana-db-storage
