---
datasources:
- name: 'Graphite'
  type: 'graphite'
  access: 'proxy'
  url: 'http://graphite:80'
  is_default: true
  version: 1
  editable: true
---  
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  isDefault: true
  url: http://prometheus:9090
  editable: true