{
 "title": "Collectd graphs",
 "description": "CollectD & Graphite Server Metrics Dashboard with  CPU, Memory, IO & Disk Stats",
 "tags": [ "collectd" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prefix", "query": "collectd" },
   { "name": "server", "query": "$prefix.*" }
  ]
 },
 "panels": [
  {
   "title": "Basic metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Average",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasByNode($prefix.$server.aggregation.cpu-average.cpu.{system,wait,user}, 5)"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bits" }
     ],
     "targets": [
      {
       "target": "aliasByNode($prefix.$server.memory.memory.{cached,free,buffered}, 4)"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode($prefix.$server.load.load.shortterm, 4)"
      }
     ]
    },
    {
     "title": "Process Fork/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode($prefix.$server.processes.fork_rate, 3)"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode($prefix.$server.processes.ps_state.*, 4)"
      }
     ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond($prefix.$server.disk.*.disk_ops.read), 3)"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond($prefix.$server.disk.*.disk_ops.write), 3)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.df.*.df_complex.used, 3, 5)"
    },
    {
     "target": "aliasByNode($prefix.$server.df.*.df_complex.free, 3, 5)"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.swap.swap.*, 4)"
    }
   ]
  },
  {
   "title": "Disk traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.disk.*.disk_octets.*, 3, 5)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Network Traffic/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.interface.*.if_octets.*, 3, 5)"
    }
   ]
  },
  {
   "title": "Network Packets/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond($prefix.$server.interface.*.if_packets.rx), 3, 5)"
    },
    {
     "target": "aliasByNode(perSecond($prefix.$server.interface.*.if_packets.tx), 3, 5)"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory per processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "aliasByNode($prefix.lin1.processes.ps_state.*, 4)\n\n\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "target": "aliasByNode($prefix.$server.processes.*.ps_rss, 3)"
      }
     ]
    },
    {
     "title": "disk io of processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "aliasByNode($prefix.lin1.processes.ps_state.*, 4)\n\n\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "target": "aliasByNode(collectd.$server.processes.*.ps_disk_octets.*, 3, 5)"
      }
     ]
    },
    {
     "title": "Number of processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(collectd.$server.processes.*.ps_count.threads, 3, 5)"
      }
     ]
    },
    {
     "title": "cpu time of processes",
     "type": "graph",
     "description": "correlates with  % of used CPU resource",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      {
       "format": "short",
       "label": "correlates with  % of used CPU resource"
      }
     ],
     "targets": [
      {
       "target": "aliasByNode(asPercent(collectd.$server.processes.*.ps_cputime.user, 1500000), 3)"
      }
     ]
    }
   ]
  },
  { "title": "TCP connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "tcp connections 80-local",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.tcpconns.80-local.tcp_connections.*, 5)"
    }
   ]
  },
  {
   "title": "tcp connections 443-local",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.tcpconns.443-local.tcp_connections.*, 5)"
    }
   ]
  },
  {
   "title": "PHP-FPM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "PHP-FPM static",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode($prefix.$server.curl_json.fpm.tcp_connections.*, 5)"
      }
     ]
    },
    {
     "title": "PHP-FPM dynamic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "none", "label": "Requests/sec" }
     ],
     "targets": [
      {
       "target": "alias($prefix.$server.curl_json.fpm.apache_requests.accepted_conn, 'req/s')"
      }
     ]
    }
   ]
  },
  { "title": "Apache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Apache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$server.apache.apache.apache_connections, 4)"
    },
    {
     "target": "aliasByNode($prefix.$server.apache.apache.apache_idle_workers, 4)"
    }
   ]
  },
  {
   "title": "Apache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias($prefix.$server.apache.apache.apache_requests, 'req/s')"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode($prefix.$server.nginx.nginx_connections.*, 4)"
      }
     ]
    },
    {
     "title": "Nginx",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias($prefix.$server.nginx.nginx_requests, 'req/s')"
      }
     ]
    },
    {
     "title": "Nginx errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias($prefix.$server.tail.nginx.derive.errors, 'errors/s')"
      },
      {
       "target": "alias(scale(summarize($prefix.$server.tail.nginx.derive.errors, '10m', 'sum', false), 10), 'total per 10m')"
      },
      {
       "target": "alias(integral(scale($prefix.$server.tail.nginx.derive.errors, 10)), 'total')"
      }
     ]
    }
   ]
  }
 ]
}